org: shawnhosea
app: sls-crud
service: sls-crud
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  provider:
  httpApi:
    cors: true
  environment:
    DYNAMODB_CUSTOMER_TABLE: ProductsTable
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/ProductsTable

functions:
  createProduct:
    handler: createProduct.createProduct
    events:
      - httpApi:
          path: /product
          method: post
  getProduct:
    handler: getProduct.getProduct
    events:
      - httpApi:
          path: /product/{id}
          method: get
  updateProduct:
    handler: updateProduct.updateProduct
    events:
      - httpApi:
          path: /product/{id}
          method: put
  deleteProduct:
    handler: deleteProduct.deleteProduct
    events:
      - httpApi:
          path: /product/{id}
          method: delete
  listProduct:
    handler: listProduct.listProduct
    events:
      - httpApi:
          path: /products
          method: get
resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: productID
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: productID
            KeyType: HASH
        TableName: ProductsTable